name: deploy to s3
on:
  # comment out following three lines if you want to deploy automatically
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checout
        uses: actions/checkout@v2

      - name: module install
        run: npm install

      - name: Build book
        run: npm run build

      - name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          # change "your.domain.name" to real domain you use.
          # this value has to be the same with the domain specified in "create-s3.yml"
          YOUR_DOMAIN_NAME: your.domain.name
        run: aws s3 sync --delete _book/ s3://${YOUR_DOMAIN_NAME}
